add rvm init and config to restart-thin

diff --git a/restart-thin b/restart-thin
--- a/restart-thin
+++ b/restart-thin
@@ -3,6 +3,19 @@
 PIDFILE=tmp/pids/thin.pid
 RAILS_ENV=production
 
+rvm_env="/usr/local/rvm/scripts/rvm"
+
+if [[ -s $rvm_env ]]; then
+  source $rvm_env  # This loads RVM into a shell session.
+else
+  printf "ERROR: An RVM installation was not found.\n" && exit 1
+fi
+
+# use ruby specified in project .rvmrc
+export rvm_project_rvmrc=1
+export rvm_trust_rvmrcs_flag=1
+export rvm_ignore_rvmrc=0
+
 action='start'
 
 if [ -e "$PIDFILE" ]; then
